language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - START_TIME=`date +%s`
  - python main.py -quick || exit 1
  - |
    END_TIME=`date +%s`; 
    RUNTIME=$((END_TIME - START_TIME)); 
    echo "Program ran in: " $RUNTIME " seconds"
  - >
    linterrating=`pylint 
    components/ 
    --disable=C0103 
    --disable=C0321 
    --disable=C0116 
    --disable=C0114 
    --disable=R0903 
    --disable=E0401
    | grep 'rated at'
    | awk '{print $7}'`
    && num=${linterrating:0:1} 
    && echo "Linter score: " $linterrating; 
    if [ "$num" -lt 9 ]; 
        then echo "linter failed" && exit 1; 
        else echo "linter passed"; 
    fi;
  - |
    FOLDER="$PWD/files/output"
    NUM_FILES=`ls -1 $FOLDER | wc -l`
    if [ "$NUM_FILES" -lt 5 ];
        then echo "Generated files don't exist" && exit 1;
        else echo "Generated files exist";
    fi;